services:
  # Kafka services
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true

  cassandra:
    image: cassandra:3.11.8
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - TZ=Europe/Warsaw
      - CASSANDRA_CLUSTER_NAME=RedirectCluster
      - CASSANDRA_DC=datacenter1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_SEEDS=cassandra
      - MAX_HEAP_SIZE=1024M
      - HEAP_NEWSIZE=256M
    volumes:
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

  cassandra-init:
    image: cassandra:3.11.8
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - TZ=Europe/Warsaw
    volumes:
      - /etc/localtime:/etc/localtime:ro
    command: >
      cqlsh cassandra -e "
      CREATE KEYSPACE IF NOT EXISTS redirect_keyspace 
      WITH REPLICATION = { 
        'class' : 'SimpleStrategy', 
        'replication_factor' : 1 
      }; 
      USE redirect_keyspace;
      CREATE TABLE IF NOT EXISTS short_url_entity (
        short_key text PRIMARY KEY,
        original_url text,
        expiration_time bigint,
        creation_time bigint,
        last_access_time bigint
      );"

  shortener-service:
    build:
      context: ./shorturl2
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      cassandra:
        condition: service_healthy
      kafka:
        condition: service_started
    environment:
      - TZ=Europe/Warsaw
      - SPRING_DATA_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_DATA_CASSANDRA_KEYSPACE_NAME=redirect_keyspace
      - SPRING_DATA_CASSANDRA_LOCAL_DATACENTER=datacenter1
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    volumes:
      - /etc/localtime:/etc/localtime:ro

  redirect-service:
    build:
      context: ./read_redirect
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - TZ=Europe/Warsaw
      - SPRING_DATA_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_DATA_CASSANDRA_KEYSPACE_NAME=redirect_keyspace
      - SPRING_DATA_CASSANDRA_LOCAL_DATACENTER=datacenter1
    volumes:
      - /etc/localtime:/etc/localtime:ro

  cleanup-service:
    build:
      context: ./cleanup_service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    depends_on:
      cassandra:
        condition: service_healthy
    environment:
      - TZ=Europe/Warsaw
      - SPRING_DATA_CASSANDRA_CONTACT_POINTS=cassandra
      - SPRING_DATA_CASSANDRA_KEYSPACE_NAME=redirect_keyspace
      - SPRING_DATA_CASSANDRA_LOCAL_DATACENTER=datacenter1
    volumes:
      - /etc/localtime:/etc/localtime:ro